# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Writing mikutter plugin
description: "It's mikutter!"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://reference.mikutter.hachune.net" # the base hostname & protocol for your site
# twitter_username: toshi_a
# github_username:  toshia

# Build settings
markdown: kramdown

exclude: ["vendor"]

sass:
  style: compressed
  sass_dir: _sass
